platform:
  - x86
  - x64
  - Any CPU

environment:
  matrix:
    - nodejs_version: "7"
    - nodejs_version: "6"
    - nodejs_version: "5"
    - nodejs_version: "4"

install:
  - npm install

matrix:
  fast_finish: true

build: off

test_script:
  - npm test
